### ISSUE TITLE
Specify width and height in numbers

### ISSUE THREAD

**Issue by ghost** [LukeStorry/bool-array-filler#1]
Is it possible to adjust the width and height through input boxes where you enter numbers, rather than having to count what the starting size is and adding each individually row/column manually?

**Comment by LukeStorry** [comment]
It certainly is!

If you want to make that change I'll accept the PR, otherwise give me a
couple of days and I'll do it :smile:

**Comment by ghost** [comment]
I might give it a shot tomorrow. :)

**Comment by LukeStorry** [comment]
I had a spare half hour, done!

Let me know if you have any other suggestions 👍
